### ISSUE TITLE
Add a measurement intervall between readings 

### ISSUE THREAD

**Issue by ClemensGruber** [Hiverize/FiPy#1]
Currently the software starts a new reading after finishing the last round of sensor reading and submitting data. Would be great to add a measurement intervall in the settings file and implement a simple wait periode after last reading. 

- intervall in seconds 
- start time is before reading sensors so 
waiting time = sensor reading - data submission 
- so we have to check if wait time is negative in case it si very short

**Comment by vkuhlen** [comment]
I implemented a time.sleep between measurements, the interval can changed in the webinterface in "General settings".
