### ISSUE TITLE
do not generate *.plt file on SD card

### ISSUE THREAD

**Issue by ClemensGruber** [Hiverize/FiPy#27]
With the latest changes from Didi a code part is new in master that generates a *.plt file on the SD card. I think this is fot Didi's local purpose only and confuses other user, so we should not stay this in the master branch but deleted. Further details needed what we must delete here.

**Comment by DieDiren** [comment]
sollte hiermit gefixt sein: https://github.com/Hiverize/FiPy/commit/6829536898d919aff2da1f2d72ec5a639467b42a

**Comment by ClemensGruber** [comment]
Danke, ja funktioniert!
