### ISSUE TITLE
wrong initialization Wifi interface 

### ISSUE THREAD

**Issue by ClemensGruber** [Hiverize/FiPy#29]
see https://community.hiveeyes.org/t/verbesserung-der-stabilitat-der-bob-firmware/2957/115

> 
> Das WLAN-Interface wird doppelt initialisiert.
> 
>     FiPy/main.py at 491550b6604df6d1d77fc00baa6fd565fe91be69 · Hiverize/FiPy · GitHub 2
>     FiPy/main.py at 491550b6604df6d1d77fc00baa6fd565fe91be69 · Hiverize/FiPy · GitHub 1
> 
> Einmal reicht und verwirrt das Gerät dann hoffentlich nicht mehr.

**Comment by DieDiren** [comment]
sollte hiermit gefixt sein: https://github.com/Hiverize/FiPy/commit/6829536898d919aff2da1f2d72ec5a639467b42a
